dist: trusty
sudo: required
language: python
python:
  - "3.6"
install:
  - "sudo apt-get -y update"
  - "sudo apt-get -y install inkscape icnsutils python3-pip"
  - "pip3 install json-spec cairosvg pylint"
script: 
  - "pylint --disable=C0103 gen.py"
  - "cd ./tests/"
  - "python3 validate-json.py"
  - "python3 order.py"
