dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "sudo apt-get -y update"
  - "sudo apt-get -y install inkscape icnsutils python3-pip"
  - "pip3 install json-spec cairosvg"
script: 
  - "python3 ./tests/validate-json.py"
