sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "sudo apt-get -y update"
  - "sudo apt-get install inkscape icnsutils"
  - "pip install json-spec cairosvg"
script: 
  - "json validate --schema-file=schema.json --document-file=data.json"
